INSERT INTO budget_code (code, description) VALUES (10000, 'telephone (line & internet)');
INSERT INTO budget_code (code, description) VALUES (10010, 'Supplies & materials');
INSERT INTO budget_code (code, description) VALUES (10020, 'Copy machine rental');
INSERT INTO budget_code (code, description) VALUES (10030, 'Postage & courier');
INSERT INTO budget_code (code, description) VALUES (10040, 'Advertizement');
INSERT INTO budget_code (code, description) VALUES (10100, 'Publication subscription');
INSERT INTO budget_code (code, description) VALUES (10200, 'Membership fee');
INSERT INTO budget_code (code, description) VALUES (10300, 'Software subscription');
INSERT INTO budget_code (code, description) VALUES (10400, 'Local transportations');
INSERT INTO budget_code (code, description) VALUES (10500, 'Travel / Transportation');
INSERT INTO budget_code (code, description) VALUES (10510, 'Lodging');
INSERT INTO budget_code (code, description) VALUES (10600, 'Fixture/furniture');
INSERT INTO budget_code (code, description) VALUES (10700, 'Auto payment');
INSERT INTO budget_code (code, description) VALUES (10710, 'Auto Supplies & materials');
INSERT INTO budget_code (code, description) VALUES (10720, 'Auto Rental');
INSERT INTO budget_code (code, description) VALUES (10800, 'Support / assistance');
INSERT INTO budget_code (code, description) VALUES (10900, 'Honorarium (guest speaker)');
INSERT INTO budget_code (code, description) VALUES (11000, 'Entertainment / food');
INSERT INTO budget_code (code, description) VALUES (11100, 'Special event (External)');
INSERT INTO budget_code (code, description) VALUES (11200, 'Special event (Internal)');
INSERT INTO budget_code (code, description) VALUES (11300, 'Lunch sale preparation');
INSERT INTO budget_code (code, description) VALUES (12000, 'Gas/electric');
INSERT INTO budget_code (code, description) VALUES (13000, 'Audio/Video equipment');
INSERT INTO budget_code (code, description) VALUES (20100, 'Trash removal');
INSERT INTO budget_code (code, description) VALUES (20200, 'Security service');
INSERT INTO budget_code (code, description) VALUES (20300, 'Snow removal');
INSERT INTO budget_code (code, description) VALUES (20400, 'Landscape');
INSERT INTO budget_code (code, description) VALUES (20500, 'Equipment');
INSERT INTO budget_code (code, description) VALUES (20600, 'Maintenance Fee');
INSERT INTO budget_code (code, description) VALUES (20700, 'Equipment Rental');
INSERT INTO budget_code (code, description) VALUES (20800, 'Donated Facilities Maintenance');
INSERT INTO budget_code (code, description) VALUES (20900, 'Church cleaning');
INSERT INTO budget_code (code, description) VALUES (30000, 'Renew/ Registration');
INSERT INTO budget_code (code, description) VALUES (30100, 'Female Retreat');
INSERT INTO budget_code (code, description) VALUES (30200, 'Enoch ministry support');
INSERT INTO budget_code (code, description) VALUES (30300, 'Curriculum');
INSERT INTO budget_code (code, description) VALUES (30400, 'Conference & Training');
INSERT INTO budget_code (code, description) VALUES (30500, 'VBS');
INSERT INTO budget_code (code, description) VALUES (30600, 'Awana');
INSERT INTO budget_code (code, description) VALUES (30700, 'Visitation');
INSERT INTO budget_code (code, description) VALUES (30800, 'Outreach');
INSERT INTO budget_code (code, description) VALUES (40200, 'Meetings');
INSERT INTO budget_code (code, description) VALUES (40300, 'Guidance Team');
INSERT INTO budget_code (code, description) VALUES (50010, 'BWI mission');
INSERT INTO budget_code (code, description) VALUES (50020, 'Salaam Center');
INSERT INTO budget_code (code, description) VALUES (50030, 'Good spoon');
INSERT INTO budget_code (code, description) VALUES (50040, 'Kid''s EE');
INSERT INTO budget_code (code, description) VALUES (50050, 'GMK');
INSERT INTO budget_code (code, description) VALUES (50060, 'Short Term Mission');
INSERT INTO budget_code (code, description) VALUES (50070, 'Peru');
INSERT INTO budget_code (code, description) VALUES (50080, 'Tanzania');
INSERT INTO budget_code (code, description) VALUES (50090, 'Jordan');
INSERT INTO budget_code (code, description) VALUES (50100, 'Ethiopia');
INSERT INTO budget_code (code, description) VALUES (50110, 'Albania');
INSERT INTO budget_code (code, description) VALUES (50120, 'Kosovo');
INSERT INTO budget_code (code, description) VALUES (50130, 'Krygystan');
INSERT INTO budget_code (code, description) VALUES (50140, 'Brazil');